### ISSUE TITLE
Latest version (2.1.4) doesn't use the host param when calling createApp in top-level-oauth-redirect.ts

### ISSUE THREAD

**Issue by eyal0s** [TheSecurityDev/simple-koa-shopify-auth#12]
Noticed that this was solved with https://github.com/TheSecurityDev/simple-koa-shopify-auth/commit/f7aff2a9e5eec31564503e571b89ef89e97a02b9

Can you please say when you going to create a new release? 
Shopify required us to adapt to the new admin.shopify.com host scheme and it looks like this issue is a blocker for us atm.

Thank you very much!

**Comment by TheSecurityDev** [comment]
The latest version on NPM is actually 2.1.5. For some reason I never made a release on Github (I think I was still testing it). But it should work fine.

**Comment by TheSecurityDev** [comment]
Actually I guess v2.1.5 doesn't have the commit you referenced, so I guess I need to make a new one.

**Comment by TheSecurityDev** [comment]
Okay, the latest version is now 2.1.6, which should fix any issues (and hopefully not create new ones). Reopen this if it doesn't work.
