### ISSUE TITLE
ReferenceError: btoa is not defined

### ISSUE THREAD

**Issue by jamesii-four13** [TheSecurityDev/simple-koa-shopify-auth#13]
![image](https://user-images.githubusercontent.com/104698050/202991308-7722dc0b-0cdf-4e1f-8650-6bc99f0dace9.png)

**Comment by TheSecurityDev** [comment]
I think this should be fixed in 2.1.8 now.

**Comment by jamesii-four13** [comment]
I'm still having issues with btoa is not defined.

**Comment by TheSecurityDev** [comment]
Is this an error in the client or browser? What version are you using?

**Comment by ssauli** [comment]
I am having this issue as well. Everything seems to work correctly if I run my koa app locally and serve it through ngrok, but once I build and deploy the app, Koa app gives the following error when requesting the install route:

```
  ReferenceError: btoa is not defined
      at /var/task/node_modules/simple-koa-shopify-auth/lib/top-level-oauth-redirect.js:82:24
      at Generator.next (<anonymous>)
      at fulfilled (/var/task/node_modules/simple-koa-shopify-auth/lib/top-level-oauth-redirect.js:5:58)
```

I am running:
- @shopify/shopify-api 5.0.1
- simple-koa-shopify-auth 2.1.8

**Comment by TheSecurityDev** [comment]
Ok, something went wrong and the new update was never built. So 2.1.9 should fix it.
