### ISSUE TITLE
LRUCache is not a constructor

### ISSUE THREAD

**Issue by Gulshanaggarwal** [TheSecurityDev/simple-koa-shopify-auth#19]
**What is the error?**
When I'm upgrading shopify polaris version from 6.2.0 to latest it says lru-cache not found. After installing lru-cache package it gives me this **LRUCache is not a constructor** error.

**See the image below -**
![image](https://github.com/TheSecurityDev/simple-koa-shopify-auth/assets/58553401/8fa89133-720b-413d-a277-f22c89ed3cd9)

**System Specifications-**
Windows 10
Node version - 14.20.0
NPM - 6.14.17
Shopify Polaris - 6.2.0
simple-koa-shopify-auth - 2.1.16

**Comment by Gulshanaggarwal** [comment]
> **What is the error?** When I'm upgrading shopify polaris version from 6.2.0 to latest it says lru-cache not found. After installing lru-cache package it gives me this **LRUCache is not a constructor** error.
> 
> **See the image below -** ![image](https://user-images.githubusercontent.com/58553401/238604736-8fa89133-720b-413d-a277-f22c89ed3cd9.png)
> 
> **System Specifications-** Windows 10 Node version - 14.20.0 NPM - 6.14.17 Shopify Polaris - 6.2.0 simple-koa-shopify-auth - 2.1.16

@TheSecurityDev @regexj @deniz-lktr

**Comment by TheSecurityDev** [comment]
@Gulshanaggarwal Should be fixed by the latest version 2.1.17.

**Comment by Gulshanaggarwal** [comment]
Thanks @TheSecurityDev  this latest version 2.1.17 solved our issue.
