### ISSUE TITLE
Shopify.utils.validateShop has been deprecated

### ISSUE THREAD

**Issue by FourLineCode** [TheSecurityDev/simple-koa-shopify-auth#8]
Shopify.utils.validateShop has been deprecated. Is it possible to update the package to support shopify node api v5.0.0?

**Comment by TheSecurityDev** [comment]
I created a new version 1.0.6 that should fix the issues. The peer dependency is still set to v2.0.0, so let me know if that causes any issues.

**Comment by FourLineCode** [comment]
Its working fine .. Thanks for quick response <3

**Comment by TheSecurityDev** [comment]
Yeah, I also went ahead and bumped the Shopify API peer dependency to v5.0.0 and changed the package version to v2.0.0
