### ISSUE TITLE
"Internal Server Error" message when first time installed an app, but app works fine after reload page.

### ISSUE THREAD

**Issue by FourLineCode** [TheSecurityDev/simple-koa-shopify-auth#9]
When I install an app using this package for auth, it shows message "Internal Server Error"
![MicrosoftTeams-image](https://user-images.githubusercontent.com/56719270/186393522-4f6a0b80-8130-406e-aa3c-cf7eee2f7c9a.png)

But after this message, when reloaded the page, the app works fine. This problem is consistent accross any store when installed an app for the first time. I pulled up the logs from the server and this is what I found.
![image](https://user-images.githubusercontent.com/56719270/186393403-2a9fb94d-7a4f-4ff5-91a5-1b96eb9e6b8c.png)

Not sure if this is an issue with this library, but I am not accessing any id property on my `createShopifyAuth` call.

**Comment by TheSecurityDev** [comment]
Can this be reproduced in a development environment? I don't see anywhere where an id is being accessed in that part of the code, so it's either in the Shopify API library or in your code. Could you share the entire code you're using for the `afterAuth` function? Unfortunately the error message isn't very helpful because it doesn't show where the id failed to be read.

The second error message is a Shopify server error, so I would assume it's because the session wasn't created properly or something.

**Comment by TheSecurityDev** [comment]
Just to confirm is this happening in development or production?

**Comment by FourLineCode** [comment]
This is happening in production, on a heroku deployment. And it might not be related to this library. I have done some digging, and it might be something to do with `Shopify.Utils.loadCurrentSession`. So, probably can close the issue for now.

Also heres the full code for afterAuth - 
```javascript
server.use(
    createShopifyAuth({
      accessMode: "offline",
      afterAuth: async (ctx) => {
        const { shop, accessToken, scope } = ctx.state.shopify;
        ACTIVE_SHOPIFY_SHOPS[shop] = scope;
        ctx.query.token = accessToken;

        // Store shop scopes and access token in firestore
        await setDoc(doc(db, "tokens", shop), {
          shop,
          scope,
          accessToken,
        });

        // Register all webhooks
        const responses = await Promise.all(
          webhooks.map(({ topic }) =>
            Shopify.Webhooks.Registry.register({
              topic,
              shop,
              accessToken,
              path: "/webhooks",
            })
          )
        );

        responses.forEach((response, index) => {
          const topic = webhooks[index].topic;
          if (!response[topic].success) {
            console.log(`Failed to register ${topic} webhook: ${response.result}`);
          }
        });

        // NOTE: This currently doesnt work as heroku deployment restarts after 30 mins of inactivity and removes all existing data
        // Deleting metafield on app reinstall if in production only
        // if (!DEV && responses[0].APP_UNINSTALLED.success) {
        //   await deleteAllMetafield({ shop, accessToken });
        // }

        await Promise.all([
          // Save the default settings object
          saveDefaultSettings(shop, accessToken),
          // Update the default store theme
          updateTheme(shop, accessToken),
          // Create a default collection
          createCollection(shop, accessToken),
        ]);

        ctx.redirect(`https://${shop}/admin/apps/${process.env.SHOPIFY_API_KEY}`);
      },
    })
  );
```

**Comment by TheSecurityDev** [comment]
Most likely it's in your load session function which gets called by the Shopify library when this library does the authentication, which causes the error to appear like it's coming from this package. I would add a try-catch block around your load session function to see if you can track down the error. Feel free to reopen this issue if you think it is an issue after all.
